version: "3"

services:
  web:
    container_name: web
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - app
  app:
    build: .
    container_name: app
    restart: always
    command: gunicorn -b 0.0.0.0:4000 "app:create_app()"
    env_file: ./environments/app.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

