version: "3"

services:
  web:
    container_name: web
    build: ./nginx
    volumes:
      - static_volume:/home/app/app/static
    ports:
      - 8080:80
    depends_on:
      - app
  app:
    build: .
    container_name: app
    restart: always
    volumes:
      - static_volume:/home/app/app/static
    command: gunicorn -b 0.0.0.0:4000 -w 8 "app:create_app()"
    env_file: ./environments/app.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
volumes:
  static_volume:
