[default]
FLASK_ADMIN_SWATCH = "cosmo"
SQLALCHEMY_TRACK_MODIFICATIONS=false

EXTENSIONS = [
  "flask_babel:Babel",
  "app.routes:init_app",
  "app.admin:init_app",
  "app.filters:init_app",
]

[development]
DEBUG=true
SQLALCHEMY_DATABASE_URI="sqlite:///dev.db"

[production]
SQLALCHEMY_DATABASE_URI="@format {env[DB_CONNECTION]}"

[testing]
SECRET_KEY="testing"
TESTING=true
WTF_CSRF_ENABLED=false
SQLALCHEMY_DATABASE_URI="sqlite://"