[default]
FLASK_ADMIN_SWATCH = "cosmo"
SQLALCHEMY_TRACK_MODIFICATIONS=false


[development]
DEBUG=true
SQLALCHEMY_DATABASE_URI="sqlite:///dev.db"

[production]

[testing]
TESTING=true
SQLALCHEMY_DATABASE_URI="sqlite:///test.db"